
export const tasks = [
    ["..has the longest name?", "	", "100"],
    ["…traveled the furthest to get here?", "	", "100"],
    ["…traveled the least to get here?", "	", "100"],
    ["...is the most dehydrated?", "	", "250"],
    ["	Video of this scholar drinking water", "	", "500"],
    ["...is the most hungry?", "	", "250"],
    ["	Video of this scholar eating", "	", "500"],
    ["…is the most jetlagged?	", "	", "250"],
    ["	Photo of this scholar asleep", "	", "500"],
    ["…is the oldest?", "	", "100"],
    ["…has the most pets?", "	", "100"],
    ["…has the most alpacas?", "	", "100"],
    ["...can remember everyone’s names?", "	", "100"],
    ["	This scholar reciting everyone’s names", "	", "500"],
    ["...can remember what city everyone is from?", "	", "100"],
    ["	This scholar reciting everyone’s cities", "	", "500"],
    ["…can do the most push-ups?", "	", "100"],
    ["	This scholar doing push-ups", "	", "50 per"],
    ["…looks the most like a staff member? ", "	", "250"],
    ["	Photo of this scholar with their staff doppelganger", "	", "900"],
    ["…is the shortest?", "	", "100"],
    ["…is the tallest?", "	", "100"],
    ["	Tallest person lifting shortest", "	", "500"],
    ["	Shortest person lifting tallest", "	", "500"],
    ["…is the best singer?", "	", "100"],
    ["	Video of this person singing", "	", "500"],
    ["…is the worst singer?", "	", "100"],
    ["	Video of this person singing", "	", "750"],
    ["	A duet between best and worst singers", "	", "900"],
    ["…has the best haircut?", "	", "100"],
    ["…gives the best haircuts?", "	", "500"],
    ["	Video of this person giving a haircut", "	", "900"],
    ["…is the most awkward?", "	", "100"],
    ["	Video of this person being awkward", "	", "500"],
    ["	Entire team being awkward", "	", "750"],
    ["…is the best debater?", "	", "100"],
    ["	Argument over who the best debater is", "	", "500"],
    ["…is the best writer?", "	", "100"],
    ["	Something short written by that scholar", "	", "500"],
    ["…is the best Challenge-taker?", "	", "100"],
    ["	That scholar showing how to fill a bubble", "	", "500"],
    ["…is the best Bowler?", "	", "100"],
    ["	That scholar being bowled over", "	", "500"]
]