
export const tasks = [
    ["..has the longest name?", "	", "100"],
    ["…traveled the furthest to get here?", "	", "100"],
    ["…traveled the least to get here?", "	", "100"],
    ["...is the most dehydrated?", "	", "250"],
    ["	Video of this scholar drinking water", "	", "500"],
    ["...is the most hungry?", "	", "250"],
    ["	Video of this scholar eating", "	", "500"],
    ["…is the most jetlagged?	", "	", "250"],
    ["	Photo of this scholar asleep", "	", "500"],
    ["…is the oldest?", "	", "100"],
    ["…has the most pets?", "	", "100"],
    ["…has the most alpacas?", "	", "100"],
    ["...can remember everyone’s names?", "	", "100"],
    ["	This scholar reciting everyone’s names", "	", "500"],
    ["...can remember what city everyone is from?", "	", "100"],
    ["	This scholar reciting everyone’s cities", "	", "500"],
    ["…can do the most push-ups?", "	", "100"],
    ["	This scholar doing push-ups", "	", "50 per"],
    ["…looks the most like a staff member? ", "	", "250"],
    ["	Photo of this scholar with their staff doppelganger", "	", "900"],
    ["…is the shortest?", "	", "100"],
    ["…is the tallest?", "	", "100"],
    ["	Tallest person lifting shortest", "	", "500"],
    ["	Shortest person lifting tallest", "	", "500"],
    ["…is the best singer?", "	", "100"],
    ["	Video of this person singing", "	", "500"],
    ["…is the worst singer?", "	", "100"],
    ["	Video of this person singing", "	", "750"],
    ["	A duet between best and worst singers", "	", "900"],
    ["…has the best haircut?", "	", "100"],
    ["…gives the best haircuts?", "	", "500"],
    ["	Video of this person giving a haircut", "	", "900"],
    ["…is the most awkward?", "	", "100"],
    ["	Video of this person being awkward", "	", "500"],
    ["	Entire team being awkward", "	", "750"],
    ["…is the best debater?", "	", "100"],
    ["	Argument over who the best debater is", "	", "500"],
    ["…is the best writer?", "	", "100"],
    ["	Something short written by that scholar", "	", "500"],
    ["…is the best Challenge-taker?", "	", "100"],
    ["	That scholar showing how to fill a bubble", "	", "500"],
    ["…is the best Bowler?", "	", "100"],
    ["	That scholar being bowled over", "	", "500"]
]

export const tasks2 = [
    ["Entire team shouting your team name",	"V",	"1000"],
    ["Create and perform a team chant",	"V",	"1500"],
    ["Write and perform a theme song for your team",	"V",	"3000"],
    ["	Someone from another team singing your team’s song",	"V",	"5000"],
    ["Give a presentation on the person your team is named for",	"V",	"2000"],
    ["You decide! What is your team’s official favorite...", "	", "	"],
    ["	...ice cream flavor?",	"	",	"1000"],
    ["	...style of music?",	"	",	"1000"],
    ["	...pizza topping",	"	",	"1000"],
    ["	...TV show?",	"	",	"1000"],
    ["	...clothing brand?",	"	",	"1000"],
    ["	...video game?",	"	",	"1000"],
    ["	...ungulate?",	"	",	"1000"],
    ["Entire team jumping at the same time",	"P",	"1000"],
    ["	Entire team falling at the same time",	"P",	"1500"],
    ["Multiple team members reenacting a scene from a Marvel movie",	"V",	"2000"],
    ["Entire team doing the wave",	"V",	"1500"],
    ["Line your entire team up from tallest to shortest",	"P",	"1000"],
    ["	Line your team up by number of times each person has had Covid",	"P",	"1500"],
    ["	Line your team up by number of times each person has been vaccinated",	"P",	"1500"],
    ["	How many people switched places?", "P", "200 per"],
    ["Design your own Scavenge task! You’ll be given points based on impressiveness.",	"V",	"?"]
]

export const tasks3 = [
    ["Team member holding as many phones as possible", "P",	"250 per"],
    ["Team member doing a cartwheel",	"V",	"1000"],
    ["	Teach another team member to cartwheel",	"V",	"2000"],
    ["	Entire team cartwheeling",	"V",	"4000"],
    ["Team member doing a split",	"P",	"2500"],
    ["Two team members high fiving each other as much as possible in ten seconds",	"V",	"100 per"],
    ["	Team member high fiving someone from another team",	"V",	"1000"],
    ["	High five rejected ",	"V",	"-500"],
    ["Team member rehearsing their Scholar’s Show performance",	"V",	"2000"],
    ["	Team member recreating a performance from a Regional Round",	"V",	"3000"],
    ["	Entire team signing up to do a performance together",	"V",	"5000"],
    ["Team member doing an impression of a WSC staff member",	"V",	"2000"],
    ["    An impression of a WSC staff member next to that staff member",	"V",	"4000"],
    ["Team member with the most different country pins",	"P",	"100 per"],
    ["Team member doing a handstand",	"P",	"2000"],
    ["	Team member doing a headstand",	"P",	"3000"],
    ["	Team member doing a footstand",	"P",	"1"]
]

export const tasks4 = [
    ["Tell a joke to any WSC staff member",	"V",	"1000"],
    ["	Staff member laughing at the joke",	"P",	"1000"],
    ["	Staff member not laughing at the joke",	"P",	"1000"],
    ["Daniel and a blackberry croissant",	"P",	"1500"],
    ["	Daniel recounting his COVID-19 vaccinations",	"V",	"200 per"],
    ["Dylan explaining his mall rating system",	"V",	"1500"],
    ["	Dylan singing a song by The Killers",	"V",	"3000"],
    ["	Dylan teaching a class over Zoom",	"P",	"2000"],
    ["Robert is a bus driver",	"P",	"2500"],
    ["	Robert driving a bus",	"P",	"3000"],
    ["	Robert playing two truths and a lie with your team",	"V",	"2500"],
    ["Maris rating your favorite K-Pop group",	"V",	"1500"],
    ["	Maris teaching you how to make a friendship keychain",	"V",	"2000"],
    ["	Maris explaining the Vietnam visa policy",	"V",	"1500"],
    ["Chauncey teaching your team how to play My Cow",	"V",	"1000"],
    ["	Find Chauncey’s secret quarantine food blog",	"P",	"2000"],
    ["	Tell Chauncey as many cities as you can from memory in 30 seconds",	"V", "200 per"],
    ["Olivia advising your team on public health practices",	"V",	"1500"],
    ["	Ask Olivia: what is her favorite thing about living in Poland?",	"V",	"1500"],
    ["	Ask Nick: what is his favorite thing about living in Koh Samui?",	"V",	"2000"],
    ["Stephanie nyooming",	"V",	"1500"],
    ["	Take a photo of Stephanie taking a photo of your team",	"P",	"1500"],
    ["	Stephanie showing you her pet Sussy",	"P",	"2000"],
    ["Ask Vishal: what’s his Starbucks order?",	"V",	"1500"],
    ["	Vishal dancing",	"V",	"3000"],
    ["Ask Lexi: what’s her least favorite country?",	"V",	"1000"],
    ["	Ask Lexi: where does she live?",	"V",	"1000"],
    ["	Lexi speaking Spanish",	"V",	"1500"],
    ["	Lexi having a conversation with Spanish with Rosie",	"V",	"2500"],
    ["KK finding the cheapest way to get from Nha Trang to your home city",	"V",	"1500"],
    ["	KK teaching your team how to DJ",	"V",	"3000"],
    ["Ask Rosie: what are your favorite things about coyotes?",	"V",	"1500"],
    ["	Rosie doing a coyote impression",	"V",	"2000"],
    ["Jeremy telling you where the party’s at",	"V",	"2500"],
    ["	Ask Jeremy about tents in Islamabad",	"V",	"3000"],
    ["Ask Mai Chi: who is the best Genshin Impact character?",	"V",	"1500"],
    ["	Mai Chi advising your team on how to get through the park",	"V",	"1500"],
    ["Dexter driving a buggy",	"V",	"2000"]
]

export const tasks5 = [
    ["Team photo overlooking the bay",	"P",	"2500"],
    ["Show off something you own at Mine Adventure",	"P",	"1000"],
    ["	Play Minecraft at the Mine Adventure",	"V",	"1500"],
    ["Swing a teammate at the Swing Carousel",	"V",	"1500"],
    ["	Entire team rotating around a teammate at the Swing Carousel",	"V",	"1750"],
    ["Drop to the ground at Sky Drop",	"V",	"1000"],
    ["	Teammate in the sky at Sky Drop",	"P",	"2000"],
    ["Photo of entire team midair at the Bungee Jump",	"P",	"2500"],
    ["	What is the highest a teammate can jump?",  "V",	"50 per"],
    ["One team member transforming into someone else at Evolution",	"V",	"2000"],
    ["	What is your team’s favorite Pokemon?",	"P",	"1000"],
    ["Imitate a dolphin at the dolphin fountain",	"V",	"1250"],
    ["	Kiss a dolphin",	"V",	"2000"],
    ["Eat a food you brought with you at Yummy Land Restaurant",	"V",	"1000"],
    ["	Eat a teammate at Yummy Land Restaurant",	"V",	"2000"],
    ["	Eat the Scavenge",	"V",	"-500"],
    ["Chase a teammate at the Giant Sky Chaser",	"V",	"1000"],
    ["	Giantest teammate at Giant Sky Chaser",	"P",	"1250"],
    ["	Photo that makes a teammate look larger than the Giant Sky Chaser",	"P",	"2000"],
    ["Do a somersault at a roller coaster",	"V",	"1500"],
    ["	Do the Chauncey Roll at a roller coaster",	"V",	"1000"]
]

export const tasks6 = [
        ["Make a bet with a teammate at the Lotteria Restaurant",	"V",	"1000"],
    ["	Win the bet",	"V",	"1500"],
    ["	Unwin the bet",	"V",	"2000"],
    ["How many different animals can you find?",	"P",	"100 per"],
    ["	How many different animals can you find that are not in the zoo area?",	"P",	"200 per"],
    ["Stand on one leg at the flamingo pool",	"P",	"1000"],
    ["	Speak flamingo to a flamingo",	"V",	"1500"],
    ["Make something unlikely happen near a black swan",	"V",	"1250"],
    ["	Make something likely happen near a white swan",	"V",	"1000"],
    ["	Inspire a swan with the story of The Ugly Duckling",	"V",	"2000"],
    ["Teammate with the longest neck near a giraffe",	"P",	"1250"],
    ["	Lift a teammate onto your shoulders to become taller",	"P",	"2000"],
    ["Line up in backwards alphabetical order near a zebra",	"P",	"1500"],
    ["Charge at a teammate near a rhino",	"V",	"1250"],
    ["Declare a dictatorship over your team near a lion",	"V",	"1250"],
    ["	Teammate with the most majestic mane and a lion",	"P",	"1000"],
    ["Make a breeze for your team at the aviary",	"V",	"1000"],
    ["	Speak to a bird",	"V",	"1000"],
    ["	Bird speaks back",	"V",	"2000"],
    ["Enter the World Garden area",	"P",	"1000"],
    ["	How many different countries is your team from?",	"P",	"100 per"],
    ["Poke a teammate near a cactus",	"V",	"1000"],
    ["Entire team inside of a dome",	"P",	"1250"],
    ["	Teammate trapped inside of a dome",	"P",	"2000"],
    ["Speak Japanese at Japanese Garden",	"V",	"1250"],
    ["Speak Swahili at Africa Desert",	"V",	"1250"],
    ["Wave at someone in a Ferris Wheel car",	"V",	"1000"],
    ["	That person waving back",	"V",	"1750"],
    ["Teammate in a Ferris Wheel car",	"P",	"1500"],
    ["	Selfie from the top of the Ferris Wheel!",	"P",	"2500"],
    ["	Photo taken from the top of the Ferris Wheel of teammate on the ground",	"P",	"2500"],
    ["Team Naruto running down the path to the Ferris Wheel",	"V",	"3000"]
]

export const tasks7 = [
        ["Entire team on an escalator",	"P",	"1500"],
    ["	Go up a down escalator",	"V",	"2000"],
    ["	Go down an up escalator ",	"V",	"2000"],
    ["How many total steps are on the staircase beside the escalator?", 	"P",	"3000 (if correct)"],
    ["Bump into your teammate at the Crashing Rainbow bumper cars",	"V",	"1250"],
    ["	A driver’s license",	"P",	"1500"],
    ["	A “driver’s license”",	"P",	"2000"],
    ["Become friends with a pigeon",	"V",	"1250"],
    ["	Become enemies with a pigeon",	"V",	"-750"],
    ["Be basic at the Starbucks",	"V",	"1500"],
    ["	How many different stars can you name in 30 seconds?",	"V",	"150 per"],
    ["	How many different currencies can you name in 30 seconds?",	"V",	"150 per"],
    ["Whole team on the steps to the Underwater World aquarium",	"P",	"1250"],
    ["	Team member being eaten by the shark jaws",	"P",	"1500"],
    ["	Slow-motion scene near the turtles",	"V",	"1500"],
    ["	Be cold-blooded near the lizards",	"V",	"1250"],
    ["	Make the noise of a cat at a catfish",	"V",	"1000"],
    ["	Make the noise of a clown at a clownfish",	"V",	"1000"],
    ["	Make the noise of a horse at a seahorse",	"V",	"1000"],
    ["	Make the noise of a sandwich at a jellyfish",	"V",	"1000"],
    ["Grant a teammate’s wish when entering Fairy Land",	"V",	"1500"],
    ["Shine your phone’s light at Luminary Square",	"P",	"1000"],
    ["Be a royal family at Cosmo Castle",	"V",	"1250"],
    ["	Do an impression of Queen Elizabeth II",	"V",	"1500"],
    ["Walk around with your eyes closed at Dark Theater",	"V",	"1250"],
    ["Tell your teammate’s fortune through astrology at Aurazone",	"V",	"1500"],
    ["Find out a teammate’s favorite song at Booster Music Express",	"V",	"1500"],
    ["	Entire team singing that song",	"V",	"2500"],
    ["Team being a happy family at Family Land",	"V",	"1500"],
    ["	Team being a dysfunctional family at Family Land",	"V",	"2000"]
]

export const tasks8 = [
    ["Geoengineer the park",	"V",	"2000"],
["Create a space mirror",	"P",	"1500"],
["Pick up some litter and dispose of it properly",	"V",	"2000"],
["	Pick up some trash and turn it into litter",	"V",	"-5000"],
["Reenact an earthquake",	"V",	"1000"],
	["	Reenact an avalanche",	"V",	"1500"],
	["	Reenact a heat wave",	"V",	"10"],
["Fix global warming",	"V",	"20000+1 Nobel prize"],
["Find a typo on the Scavenge",	"P",	"500"],
["“Accidentally”…", "", ""],		
	["	…pocket dial someone",	"V",	"1000"],
	["	…like someone’s social media post from over two years ago",	"V",	"1250"],
	["	…hit ‘send’ on an unfinished email",	"V",	"1500"],
	["	…text someone you haven’t talked to in over a year",	"P",	"2000"],
["Hold an election for a Team Captain", 	"V",	"1000"],
	["	Team Captain giving an encouraging speech",	"V",	"1500"],
	["	Team Captain giving a threatening speech",	"V",	"2000"],
	["	Turn your Scavenge team into a monarchy",	"V",	"1500"],
["Swap an item of clothing with another Scavenge team member",	"P",	"1000"],
	["	…permanently",	"P",	"2500"],
["Invent a new word that describes someone on your Scavenge team",	"V",	"1000"],
	["	Someone from another team using that word",	"V",	"2500"],
	["	A news article using that word",	"P",	"5000"],
["Whose phone is the oldest?",	"P",	"750"],
	["	Whose phone is the newest?",	"P",	"750"],
	["	Those two scholars switching phones",	"P",	"1000"],
	["	…permanently",	"V",	"10000"],
["Beatbox along to one of this year’s songs",	"V",	"2000"],
["Write and perform a sequel to any song you like",	"V",	"3000"],
["Reenact a scene from an arcade game",	"V",	"3000"],
["Recite one of this year’s poems from memory",	"V",	"3000"]
]

export const tasks9 = [
    ["Decorate the park floor with alpacas",	"P",	"1000"],
["	Make a rainbow using the team’s Jerries",	"P",	"1250"],
["Photo with the team that arrived before you",	"V",	"1000"],
["Photo with as many teams as possible",	"P",	"500 per"],
["Team showing love for Scavenge Leader",	"V",	"3000"],
["Team member falling into the ocean",	"V",	"-100"],
["One final group hug", "P",	"20000"]
]
